# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('schedule', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LanProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lan')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profile/')),
                ('bio', models.TextField()),
                ('grade', models.CharField(choices=[('teacher', 'Lærer'), ('none', 'Ukendt'), ('13xa', '13xa'), ('14xaa', '14xaa'), ('14xab', '14xab'), ('14abc', '14xac'), ('14xad', '14xad'), ('14xar', '14xar'), ('14xaj', '14xaj')], default='none', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=8)),
                ('row', models.SmallIntegerField()),
                ('num', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='lanprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AddField(
            model_name='lanprofile',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Seat'),
        ),
        migrations.AddField(
            model_name='lan',
            name='profiles',
            field=models.ManyToManyField(through='main.LanProfile', to='main.Profile'),
        ),
        migrations.AddField(
            model_name='lan',
            name='seats',
            field=models.ManyToManyField(to='main.Seat'),
        ),
    ]
