# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='num',
            new_name='col',
        ),
    ]
