# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161031_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='lan',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='table',
        ),
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.ManyToManyField(to='main.Seat'),
        ),
        migrations.AddField(
            model_name='lan',
            name='tables',
            field=models.ManyToManyField(to='main.Table'),
        ),
    ]
