# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161031_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='lan',
            name='tables',
        ),
        migrations.AddField(
            model_name='lan',
            name='seats',
            field=models.TextField(default='AA BB CC\nAA BB CC\nAA BB CC\nAA BB CC\nAA BB CC\n\nDDDDDDDD\n\n EEEEEE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lanprofile',
            name='seat',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
