# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161103_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanprofile',
            name='seat',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
