# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161105_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanprofile',
            name='seat',
            field=models.CharField(blank=True, default='', max_length=8),
            preserve_default=False,
        ),
    ]
