# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_lan_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lan',
            name='open',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lanprofile',
            name='seat',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/', verbose_name='billede'),
        ),
    ]
