# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models
import main.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20161117_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lan',
            name='blurb',
            field=models.TextField(help_text='Teksten, specifikt til dette lan, der bliver vist på forsiden.Husk at wrappe tekst i &lt;p> tags!', verbose_name='blurb'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='end',
            field=models.DateTimeField(verbose_name='slut'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='name',
            field=models.CharField(max_length=255, verbose_name='navn'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='open',
            field=models.DateTimeField(verbose_name='tildmelding åbner'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='schedule',
            field=models.TextField(verbose_name='tidsplan'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='seats',
            field=models.TextField(verbose_name='pladser'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='start',
            field=models.DateTimeField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='lanprofile',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lan', verbose_name='lan'),
        ),
        migrations.AlterField(
            model_name='lanprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile', verbose_name='profil'),
        ),
        migrations.AlterField(
            model_name='lanprofile',
            name='seat',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='plads'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, storage=main.storage.OverwriteStorage(), upload_to=main.models.profile_picture_path, verbose_name='billede'),
        ),
    ]
