# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20161124_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='lan',
            name='paytypes',
            field=models.TextField(null=True, verbose_name='betalingstyper'),
        ),
        migrations.AddField(
            model_name='lan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='blurb',
            field=models.TextField(help_text='Teksten, specifikt til dette lan, der bliver vist på forsiden.<br>Husk at wrappe tekst i &lt;p> tags!', verbose_name='blurb'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='schedule',
            field=models.TextField(null=True, verbose_name='tidsplan'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(choices=[('16xaa', '16xaa'), ('16xab', '16xab'), ('16xac', '16xac'), ('16xad', '16xad'), ('16xae', '16xae'), ('16xaf', '16xaf'), ('16xaj', '16xaj'), ('16xap', '16xap'), ('16xar', '16xar'), ('13xa', '13xa'), ('14xaa', '14xaa'), ('14xab', '14xab'), ('14xad', '14xad'), ('14xae', '14xae'), ('14xaj', '14xaj'), ('14xap', '14xap'), ('14xaq', '14xaq'), ('14xar', '14xar'), ('15xaa', '15xaa'), ('15xab', '15xab'), ('15xac', '15xac'), ('15xad', '15xad'), ('15xae', '15xae'), ('15xaj', '15xaj'), ('15xap', '15xap'), ('15xar', '15xar'), ('teacher', 'Lærer'), ('none', 'Ukendt')], default='none', max_length=32, verbose_name='klasse'),
        ),
    ]
