# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.storage
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20161208_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='navn')),
                ('description', models.TextField(verbose_name='beskrivelse')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, storage=main.storage.OverwriteStorage(), upload_to='games/', verbose_name='billede')),
            ],
            options={
                'verbose_name': 'spil',
                'verbose_name_plural': 'spil',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='navn')),
                ('description', models.TextField(verbose_name='beskrivelse')),
                ('team_size', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game', verbose_name='spil')),
                ('lan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lan', verbose_name='lan')),
            ],
            options={
                'verbose_name': 'turnering',
                'verbose_name_plural': 'turneringer',
            },
        ),
        migrations.CreateModel(
            name='TournamentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile', verbose_name='profil')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tournament', verbose_name='turnering')),
            ],
            options={
                'verbose_name': 'turnerings tilmelding',
                'verbose_name_plural': 'turnerings tilmelding',
            },
        ),
    ]
