# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_game_tournament_tournamentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='profiles',
            field=models.ManyToManyField(through='main.TournamentProfile', to='main.Profile'),
        ),
    ]
