# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_tournament_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profiles', models.ManyToManyField(to='main.Profile', verbose_name='profiler')),
            ],
            options={
                'verbose_name': 'hold',
                'verbose_name_plural': 'hold',
            },
        ),
        migrations.RemoveField(
            model_name='tournamentprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tournamentprofile',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='profiles',
        ),
        migrations.DeleteModel(
            name='TournamentProfile',
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(to='main.TournamentTeam'),
        ),
    ]
