# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20161208_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentteam',
            name='name',
            field=models.CharField(max_length=255, verbose_name='holdnavn'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='profiles',
            field=models.ManyToManyField(to='main.Profile', verbose_name='medlemmer'),
        ),
    ]
