# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20161215_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='challonge_id',
            field=models.IntegerField(blank=True, help_text='Udfyles selv, når du trykker gem.', null=True, verbose_name='Challonge id'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='extra_challonge',
            field=models.TextField(blank=True, help_text='Advannceret: ekstra data til challonge API. Angives i JSON format.', null=True, verbose_name='Extra challonge data'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='challonge_id',
            field=models.IntegerField(blank=True, help_text='Udfyldes selv, når du trykker gem.', null=True, verbose_name='Challonge id'),
        ),
    ]
