# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20170103_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='navn')),
                ('url', models.URLField(blank=True, help_text='Valgfri. Link som kan klikkes på kalenderen.', max_length=255, null=True, verbose_name='link')),
                ('start', models.DateTimeField(null=True, verbose_name='Start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Slut')),
                ('lan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lan', verbose_name='lan')),
            ],
            options={
                'verbose_name_plural': 'begivenheder',
                'verbose_name': 'begivenhed',
            },
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Slut'),
        ),
    ]
