# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20170323_1919'),
        ('main', '0038_auto_20170323_1758'),
    ]

    operations = [
    ]
