# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:21
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_merge_20170323_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Advarsel: Dette felt overskrives af url!', null=True, verbose_name='tekst til eventside'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, help_text='Valgfri. Link som kan klikkes på kalenderen.Denne felt har større prioritet end tekst.', max_length=255, null=True, verbose_name='link'),
        ),
    ]
