# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20170702_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(default='none', max_length=32, verbose_name='klasse'),
        ),
    ]
