# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20170702_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='lan',
            name='payment_manager_id',
            field=models.CharField(blank=True, help_text='Unik token som indentificerer hvorbetalingsforespørgelser skal sendes.', max_length=128, null=True, verbose_name='Payment Manager id'),
        ),
    ]
