# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_lan_payment_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='show_on_calendar',
            field=models.BooleanField(default=True, verbose_name='Vis på kalender'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Profile', verbose_name='Ansvarlig'),
        ),
    ]
