# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 16:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20170817_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='I dansk format f.eks. "12345678"', max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$')], verbose_name='telefonnummer'),
        ),
    ]
