# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20170826_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='collected',
            field=models.BooleanField(default=False, verbose_name='afhentet'),
        ),
    ]
